version: "3.8"
services:
  mongodb:
    image : mongo
    container_name: mongodb
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/barry/mongodb/database:/data/db
    ports:
      - 27017:27017
    command: /usr/bin/mongod --bind_ip_all --replSet rs0 --journal --dbpath /data/db